 
import Header from '@components/header';
import Navbar from '@components/navbar';
import Providers from '@components/providers';
import Search from '@components/search';
import '@styles/globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <Header />
          <Navbar />
          <Search />
          {children}
        </Providers>
      </body>
    </html>
  );
}
